USER_EMAIL = "niteesh.sab27@gmail.com"

# The 16-digit App Password you generated for the account above.
USER_PASSWORD = "yzfd rrde lhuk bef"

# The email inbox where you want to read her response.
RECIPIENT_EMAIL = "sabloksabha@gmail.com"